__version__ = '0.0.1'
__author__ = 'D-Wave Systems Inc.'
__authoremail__ = 'acondello@dwavesys.com'
__description__ = 'Generic tree decomposition-based solver.'
__title__ = 'D-Wave Orang'
__copyright__ = '2018, D-Wave Systems Inc.'
